.include "asm/_CustomASMInstaller.asm"
.include "graphics/_CustomGraphics.asm"
.include "maps/_CustomMaps.asm"
.include "tilesets/_CustomTilesets.asm"
.include "tilesets/mappalettes/_CustomMapPalettes.asm"
